CREATE OR ALTER PROCEDURE ToDone.AvgFriends
AS
SELECT (CAST((SELECT COUNT(*)
FROM ToDone.FriendsUser F
INNER JOIN ToDone.Users U ON (F.User1 = U.UserID OR F.User2 = U.UserID))/2 AS FLOAT)
/
CAST(
(SELECT COUNT(*)
FROM ToDone.Users) AS FLOAT)) AS Friends
GO